{"name": "test_login[login1]", "status": "failed", "statusDetails": {"message": "AssertionError: 失败原因：密码为空\nassert False", "trace": "login = False\n\n    @pytest.mark.parametrize(\"login\", test_user_data, indirect=True)\n    def test_login(login):\n        # '''登录用例'''\n        a = login\n        print(\"测试用例中login的返回值:%s\" % a)\n>       assert a, \"失败原因：密码为空\"\nE       AssertionError: 失败原因：密码为空\nE       assert False\n\ntest_03.py:29: AssertionError"}, "parameters": [{"name": "login", "value": "{'user': 'admin1', 'psw': ''}"}], "start": 1676890605913, "stop": 1676890605913, "uuid": "2a1de433-badb-4714-ad8f-515613271d3e", "historyId": "64964907dc3ac62855f929d6527c1065", "testCaseId": "e3bec9bcd24daa2e3eda75b73c49e41f", "fullName": "test_03#test_login", "labels": [{"name": "suite", "value": "test_03"}, {"name": "host", "value": "DESKTOP-KG3DMFK"}, {"name": "thread", "value": "9788-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_03"}]}