{"name": "test_login[admin-]", "status": "failed", "statusDetails": {"message": "AssertionError: 失败原因：密码为空\nassert False == True", "trace": "user = 'admin', psw = ''\n\n    @pytest.mark.parametrize(\"user, psw\", test_login_data)\n    def test_login(user, psw):\n        # 登录用例\n        result = login(user, psw)\n>       assert result == True, \"失败原因：密码为空\"\nE       AssertionError: 失败原因：密码为空\nE       assert False == True\n\ntest_01.py:26: AssertionError"}, "parameters": [{"name": "user", "value": "'admin'"}, {"name": "psw", "value": "''"}], "start": 1676890605873, "stop": 1676890605874, "uuid": "dcc6e224-f838-4e96-8fdc-f6e1bf5a67b7", "historyId": "61afe53c48a951223ec7e74df655fc3a", "testCaseId": "37f67e951ef4b28e93b36903d15047b9", "fullName": "test_01#test_login", "labels": [{"name": "suite", "value": "test_01"}, {"name": "host", "value": "DESKTOP-KG3DMFK"}, {"name": "thread", "value": "9788-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_01"}]}